// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgsacjbeaxuxwzgaanwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnc2FjamJlYXh1eHd6Z2FhbndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODQ3NTksImV4cCI6MjA2NDA2MDc1OX0.BmK1QABs5SoSKO1CrY1mKUzp0zms7E701wfCjbVchRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);